# fly.toml app configuration file generated for legalink on 2023-11-17T10:54:14+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "legalink"
primary_region = "sin"

[build]

[env]
NODE_ENV="production"

[http_service]
  internal_port = 3000
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
